Test chinese version branch
zoff99/ToxAndroidRefImpl pull request #83
Opened 2018-09-18 08:32 UTC by katcom

Translation some of values into Chinese.

2018-10-03 11:05 UTC, zoff99 requested changes

2018-10-03 11:05 UTC, zoff99 commented on .gitignore
> +
remove unused newline

2018-10-29 11:57 UTC, zoff99 commented
@iphydf if you have time can you check those texts please?

2019-04-17 02:13 UTC, linsui commented
@zoff99 Could you tell me what I can do to help translate this app?

2019-07-27 11:54 UTC, zoff99 commented
there is a new PR for this. this one failed to compile

#99

2019-07-27 11:54 UTC, closed without merging